# Clase Práctica: Uniones de Datos y Modelado en Python con Pandas
Este notebook cubre los tipos de Joins (Inner, Left, Right, Outer), el concepto de llaves primarias y foráneas, y la aplicación práctica con el dataset de vuelos, rutas, aeronaves y aeropuertos.

## 1. Introducción a las Uniones (Joins)
Las uniones permiten vincular múltiples tablas o DataFrames mediante columnas clave (llaves primarias y foráneas), manteniendo la integridad referencial.

In [33]:
# Importación inicial de librerías
import pandas as pd
import numpy as np

print("¡Librerías importadas con éxito!")

¡Librerías importadas con éxito!

## 2. Tipos de Uniones en Pandas (`pd.merge()`)
Crearemos dos pequeñas tablas de prueba (Usuarios y Compras) para demostrar el funcionamiento exacto de cada tipo de Join.

In [34]:
# Datos de prueba
usuarios_df = pd.DataFrame({
    'ID_Usuario': [1, 2, 3],
    'Nombre': ['Ana', 'Carlos', 'Elena']
})

compras_df = pd.DataFrame({
    'ID_Compra': [101, 102, 103],
    'ID_Usuario': [1, 2, 5], # El ID 5 no existe en usuarios
    'Monto': [250, 400, 150]
})

print("--- Tabla Usuarios --- ")
display(usuarios_df)
print("--- Tabla Compras ---")
display(compras_df)

--- Tabla Usuarios ---

   ID_Usuario  Nombre
0           1     Ana
1           2  Carlos
2           3   Elena

--- Tabla Compras ---

   ID_Compra  ID_Usuario  Monto
0        101           1    250
1        102           2    400
2        103           5    150

In [35]:
# A. Inner Join (Intersección exacta)
inner_join = pd.merge(usuarios_df, compras_df, on='ID_Usuario', how='inner')
print("1. INNER JOIN (Solo coincidencias en ambas tablas):")
display(inner_join)

1. INNER JOIN (Solo coincidencias en ambas tablas):

   ID_Usuario  Nombre  ID_Compra  Monto
0           1     Ana        101    250
1           2  Carlos        102    400

In [36]:
# B. Left Outer Join (Prioriza la tabla de la izquierda)
left_join = pd.merge(usuarios_df, compras_df, on='ID_Usuario', how='left')
print("2. LEFT OUTER JOIN (Todos los usuarios, con o sin compras):")
display(left_join)

2. LEFT OUTER JOIN (Todos los usuarios, con o sin compras):

   ID_Usuario  Nombre  ID_Compra  Monto
0           1     Ana      101.0  250.0
1           2  Carlos      102.0  400.0
2           3   Elena        NaN    NaN

In [37]:
# C. Right Outer Join (Prioriza la tabla de la derecha)
right_join = pd.merge(usuarios_df, compras_df, on='ID_Usuario', how='right')
print("3. RIGHT OUTER JOIN (Todas las compras, con o sin usuario asociado):")
display(right_join)

3. RIGHT OUTER JOIN (Todas las compras, con o sin usuario asociado):

   ID_Usuario  Nombre  ID_Compra  Monto
0           1     Ana        101    250
1           2  Carlos        102    400
2           5     NaN        103    150

In [38]:
# D. Outer Join Completo (Full Outer Join)
outer_join = pd.merge(usuarios_df, compras_df, on='ID_Usuario', how='outer')
print(
    "4. FULL OUTER JOIN (Todos los registros de ambas tablas, rellenando con"
    " NaN):")
display(outer_join)

4. FULL OUTER JOIN (Todos los registros de ambas tablas, rellenando con NaN):

   ID_Usuario  Nombre  ID_Compra  Monto
0           1     Ana      101.0  250.0
1           2  Carlos      102.0  400.0
2           3   Elena        NaN    NaN
3           5     NaN      103.0  150.0

## 3. Generación del Set de Datos de Práctica
Construiremos las tablas de nuestro caso de estudio: `Flights`, `Routes`, `Aircraft` y `Airports`.

In [39]:
import pandas as pd
import numpy as np

# Simulación de la base de datos de aviación con más datos
airports_df = pd.DataFrame({
    'Airport_ID': ['JFK', 'LAX', 'ORD', 'DFW', 'ATL', 'DEN', 'SFO', 'CLT', 'SEA', 'MIA'],
    'Airport_Name': [
        'John F. Kennedy',
        'Los Angeles Intl',
        'O\'Hare International',
        'Dallas/Fort Worth Intl',
        'Hartsfield-Jackson Atlanta Intl',
        'Denver Intl',
        'San Francisco Intl',
        'Charlotte Douglas Intl',
        'Seattle-Tacoma Intl',
        'Miami Intl',
    ],
    'City': [
        'New York',
        'Los Angeles',
        'Chicago',
        'Dallas',
        'Atlanta',
        'Denver',
        'San Francisco',
        'Charlotte',
        'Seattle',
        'Miami',
    ],
    'Country': ['USA'] * 10,
})

aircraft_df = pd.DataFrame({
    'Aircraft_ID': [737, 320, 777, 330, 787, 350, 747, 100],
    'Model': [
        'Boeing 737',
        'Airbus A320',
        'Boeing 777',
        'Airbus A330',
        'Boeing 787 Dreamliner',
        'Airbus A350',
        'Boeing 747 Jumbo Jet',
        'Embraer E190',
    ],
    'FuelCostperSeatMile': [
        0.045,
        0.042,
        0.038,
        0.040,
        0.035,
        0.036,
        0.050,
        0.048,
    ],
    'Capacity': [180, 150, 350, 250, 280, 300, 450, 100],
})

routes_df = pd.DataFrame({
    'Route_ID': [
        1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20
    ],
    'Origin': [
        'JFK', 'ORD', 'LAX', 'DFW', 'ATL', 'DEN', 'SFO', 'CLT', 'SEA', 'MIA',
        'JFK', 'LAX', 'ATL', 'SFO', 'ORD', 'DFW', 'DEN', 'CLT', 'SEA', 'MIA',
    ],
    'Destination': [
        'LAX', 'JFK', 'ORD', 'ATL', 'DFW', 'SFO', 'DEN', 'MIA', 'CLT', 'SEA',
        'MIA', 'JFK', 'LAX', 'SEA', 'ATL', 'SFO', 'DFW', 'ORD', 'JFK', 'DEN',
    ],
    'Distance_Miles': [
        2475, 740, 2250, 800, 700, 900, 600, 1000, 1100, 1200, 1300, 2500,
        850, 1050, 780, 950, 720, 1150, 1250, 1350,
    ],
})

# Generate more flights over a wider date range
num_flights = 50
start_date = pd.to_datetime('2026-01-01')
end_date = pd.to_datetime('2026-03-31')

flight_data = {
    'Flight_ID': range(1001, 1001 + num_flights),
    'Route_ID': np.random.choice(routes_df['Route_ID'], num_flights),
    'Aircraft_ID': np.random.choice(aircraft_df['Aircraft_ID'], num_flights),
    'Flight_Date': [
        start_date + pd.Timedelta(days=np.random.randint((end_date - start_date).days))
        for _ in range(num_flights)
    ],
    'Passengers': np.random.randint(50, 400, num_flights),
}

flights_df = pd.DataFrame(flight_data)

print('¡Tablas de práctica generadas con éxito y ampliadas!')

¡Tablas de práctica generadas con éxito y ampliadas!

In [40]:
flights_df.to_excel('flights_data.xlsx', index=False)
print('DataFrame flights_df exportado con éxito a flights_data.xlsx')

DataFrame flights_df exportado con éxito a flights_data.xlsx

## 4. Preprocesamiento e Inspección de Datos en Python
Dando respuesta analítica a las preguntas clave del preprocesamiento:

### Esquema de `flights_df` y sus Llaves

El DataFrame `flights_df` registra información sobre cada vuelo y tiene las siguientes llaves:

*   **Llave Primaria**: `Flight_ID` (identifica un vuelo de forma única).
*   **Llaves Foráneas**:
    *   `Route_ID`: Se relaciona con `routes_df['Route_ID']` (identifica la ruta del vuelo).
    *   `Aircraft_ID`: Se relaciona con `aircraft_df['Aircraft_ID']` (identifica el tipo de aeronave utilizada en el vuelo).

### Generando el Diagrama de Relación

In [41]:
print('--- Esquema y primeras filas de la tabla Flights ---')
display(flights_df.head())

--- Esquema y primeras filas de la tabla Flights ---

   Flight_ID  Route_ID  Aircraft_ID Flight_Date  Passengers
0       1001        15          737  2026-03-13         277
1       1002         2          737  2026-03-19         112
2       1003        15          100  2026-01-16          74
3       1004        20          787  2026-02-28         155
4       1005        15          777  2026-02-03         195

In [42]:
# Pregunta 1: ¿Cuáles son las variables y su significado? (Ej. FuelCostperSeatMile)
print('--- Información estructural de la tabla Aircraft ---')
aircraft_df.info()
print(
    'Promedio de costo de combustible por milla y asiento:',
    aircraft_df['FuelCostperSeatMile'].mean(),
)

--- Información estructural de la tabla Aircraft ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Aircraft_ID          8 non-null      int64
 1   Model                8 non-null      object
 2   FuelCostperSeatMile  8 non-null      float64
 3   Capacity             8 non-null      int64
dtypes: float64(1), int64(2), object(1)
memory usage: 388.0+ bytes
Promedio de costo de combustible por milla y asiento: 0.041749999999999995

In [43]:
# Pregunta 2: ¿Se observa algún error en los datos? (Revisión de Fechas y Nulos)
flights_df['Flight_Date'] = pd.to_datetime(flights_df['Flight_Date'])
print('--- Verificación de Nulos en el dataset de Vuelos ---')
display(flights_df.isnull().sum())
print('Tipos de datos actualizados correctamente.')

--- Verificación de Nulos en el dataset de Vuelos ---

Flight_ID      0
Route_ID       0
Aircraft_ID    0
Flight_Date    0
Passengers     0
dtype: int64

Tipos de datos actualizados correctamente.

In [44]:
# Pregunta 3: ¿Posee la estructura correcta? (Filas observaciones, columnas variables)
print(
    'Dimensiones de la tabla Flights (Filas, Columnas):',
    flights_df.shape,
)
print('Primeras filas del registro de vuelos:')
display(flights_df.head())

Dimensiones de la tabla Flights (Filas, Columnas): (50, 5)
Primeras filas del registro de vuelos:

   Flight_ID  Route_ID  Aircraft_ID Flight_Date  Passengers
0       1001        15          737  2026-03-13         277
1       1002         2          737  2026-03-19         112
2       1003        15          100  2026-01-16          74
3       1004        20          787  2026-02-28         155
4       1005        15          777  2026-02-03         195

In [45]:
# Pregunta 4: ¿Existen identificadores únicos (Llaves primarias válidas)?
print(
    '¿Es Flight_ID una llave primaria única?:',
    flights_df['Flight_ID'].is_unique,
)
print('¿Es Airport_ID una llave primaria única?:',
      airports_df['Airport_ID'].is_unique)

¿Es Flight_ID una llave primaria única?: True
¿Es Airport_ID una llave primaria única?: True

In [46]:
print('\n¿Es ID_Producto una clave única?:', productos_ventas_df['ID_Producto'].is_unique)
print('¿Es Tienda una clave única?:', productos_ventas_df['Tienda'].is_unique)
print('¿Es Fecha una clave única?:', productos_ventas_df['Fecha'].is_unique)

¿Es ID_Producto una clave única?: False
¿Es Tienda una clave única?: False
¿Es Fecha una clave única?: False

In [47]:
# Crear una clave compuesta combinando 'ID_Producto', 'Tienda' y 'Fecha'
productos_ventas_df['Clave_Compuesta'] = productos_ventas_df['ID_Producto'].astype(str) + \
                                          '_' + productos_ventas_df['Tienda'] + \
                                          '_' + productos_ventas_df['Fecha']

print('\n--- Tabla con Clave Compuesta ---')
display(productos_ventas_df.head())

--- Tabla con Clave Compuesta ---

   ID_Producto Tienda       Fecha  Cantidad_Vendida   Clave_Compuesta
0          101      A  2023-01-01                10  101_A_2023-01-01
1          101      A  2023-01-01                 5  101_A_2023-01-01
2          102      B  2023-01-02                 8  102_B_2023-01-02
3          102      A  2023-01-02                12  102_A_2023-01-02
4          103      C  2023-01-03                 7  103_C_2023-01-03

In [48]:
print('\n¿Es Clave_Compuesta una clave única?:', productos_ventas_df['Clave_Compuesta'].is_unique)

¿Es Clave_Compuesta una clave única?: False

## 5. Aplicación de Uniones y Validación con el Dataset de Vuelos

Ahora, aplicaremos los diferentes tipos de `merge` a nuestros DataFrames de vuelos para ver cómo afectan la cantidad de filas y la información resultante.

### DataFrames Originales:

In [49]:
print(f"Filas en flights_df: {flights_df.shape[0]}")
print(f"Filas en routes_df: {routes_df.shape[0]}")
print(f"Filas en aircraft_df: {aircraft_df.shape[0]}")

Filas en flights_df: 50
Filas en routes_df: 20
Filas en aircraft_df: 8

### A. INNER JOIN (Vuelos y Rutas)

Un `INNER JOIN` solo conserva las filas donde hay una coincidencia en la columna clave (`Route_ID`) en *ambos* DataFrames (`flights_df` y `routes_df`).

In [50]:
flights_routes_inner = pd.merge(flights_df, routes_df, on='Route_ID', how='inner')
print(f"Shape de flights_df: {flights_df.shape}")
print(f"Shape de routes_df: {routes_df.shape}")
print(f"Shape de flights_routes_inner (INNER JOIN): {flights_routes_inner.shape}")
display(flights_routes_inner.head())

Shape de flights_df: (50, 5)
Shape de routes_df: (20, 4)
Shape de flights_routes_inner (INNER JOIN): (50, 8)

,Flight_ID,Route_ID,Aircraft_ID,Flight_Date,Passengers,Origin,Destination,Distance_Miles
0,1001,15,737,2026-03-13,277,ORD,ATL,780
1,1002,2,737,2026-03-19,112,ORD,JFK,740
2,1003,15,100,2026-01-16,74,ORD,ATL,780
3,1004,20,787,2026-02-28,155,MIA,DEN,1350
4,1005,15,777,2026-02-03,195,ORD,ATL,780

### B. LEFT JOIN (Vuelos y Rutas)

Un `LEFT JOIN` mantiene todas las filas del DataFrame de la izquierda (`flights_df`) y agrega las columnas coincidentes del DataFrame de la derecha (`routes_df`). Si no hay coincidencia, las columnas de la derecha tendrán valores `NaN`.

In [51]:
flights_routes_left = pd.merge(flights_df, routes_df, on='Route_ID', how='left')
print(f"Shape de flights_df: {flights_df.shape}")
print(f"Shape de routes_df: {routes_df.shape}")
print(f"Shape de flights_routes_left (LEFT JOIN): {flights_routes_left.shape}")
display(flights_routes_left.head())

Shape de flights_df: (50, 5)
Shape de routes_df: (20, 4)
Shape de flights_routes_left (LEFT JOIN): (50, 8)

,Flight_ID,Route_ID,Aircraft_ID,Flight_Date,Passengers,Origin,Destination,Distance_Miles
0,1001,15,737,2026-03-13,277,ORD,ATL,780
1,1002,2,737,2026-03-19,112,ORD,JFK,740
2,1003,15,100,2026-01-16,74,ORD,ATL,780
3,1004,20,787,2026-02-28,155,MIA,DEN,1350
4,1005,15,777,2026-02-03,195,ORD,ATL,780

### C. RIGHT JOIN (Vuelos y Rutas)

Un `RIGHT JOIN` mantiene todas las filas del DataFrame de la derecha (`routes_df`) y agrega las columnas coincidentes del DataFrame de la izquierda (`flights_df`). Si no hay coincidencia, las columnas de la izquierda tendrán valores `NaN`.

In [52]:
flights_routes_right = pd.merge(flights_df, routes_df, on='Route_ID', how='right')
print(f"Shape de flights_df: {flights_df.shape}")
print(f"Shape de routes_df: {routes_df.shape}")
print(f"Shape de flights_routes_right (RIGHT JOIN): {flights_routes_right.shape}")
display(flights_routes_right.head())

Shape de flights_df: (50, 5)
Shape de routes_df: (20, 4)
Shape de flights_routes_right (RIGHT JOIN): (51, 8)

,Flight_ID,Route_ID,Aircraft_ID,Flight_Date,Passengers,Origin,Destination,Distance_Miles
0,1024.0,1,350.0,2026-01-11,366.0,JFK,LAX,2475
1,1002.0,2,737.0,2026-03-19,112.0,ORD,JFK,740
2,1027.0,2,100.0,2026-03-04,78.0,ORD,JFK,740
3,1014.0,3,350.0,2026-01-19,323.0,LAX,ORD,2250
4,1036.0,3,737.0,2026-02-01,265.0,LAX,ORD,2250

### D. OUTER JOIN (Vuelos y Rutas)

Un `OUTER JOIN` (o Full Outer Join) mantiene todas las filas de *ambos* DataFrames. Si no hay coincidencia en uno de ellos, se rellenarán con `NaN`.

In [53]:
flights_routes_outer = pd.merge(flights_df, routes_df, on='Route_ID', how='outer')
print(f"Shape de flights_df: {flights_df.shape}")
print(f"Shape de routes_df: {routes_df.shape}")
print(f"Shape de flights_routes_outer (OUTER JOIN): {flights_routes_outer.shape}")
display(flights_routes_outer.head())

Shape de flights_df: (50, 5)
Shape de routes_df: (20, 4)
Shape de flights_routes_outer (OUTER JOIN): (51, 8)

,Flight_ID,Route_ID,Aircraft_ID,Flight_Date,Passengers,Origin,Destination,Distance_Miles
0,1024.0,1,350.0,2026-01-11,366.0,JFK,LAX,2475
1,1002.0,2,737.0,2026-03-19,112.0,ORD,JFK,740
2,1027.0,2,100.0,2026-03-04,78.0,ORD,JFK,740
3,1014.0,3,350.0,2026-01-19,323.0,LAX,ORD,2250
4,1036.0,3,737.0,2026-02-01,265.0,LAX,ORD,2250

### Combinación de Múltiples Uniones (Flights, Routes y Aircraft)

Ahora, vamos a realizar una cadena de `INNER JOIN` para combinar la información de vuelos, rutas y aeronaves. Este es un escenario común para construir una tabla "maestra" de datos interconectados.

In [54]:
print(f"Filas en flights_df: {flights_df.shape[0]}")
print(f"Filas en routes_df: {routes_df.shape[0]}")
print(f"Filas en aircraft_df: {aircraft_df.shape[0]}")

# Primer INNER JOIN: flights_df con routes_df
flights_routes_merged = pd.merge(flights_df, routes_df, on='Route_ID', how='inner')
print(f"Filas después de flights_df + routes_df (INNER): {flights_routes_merged.shape[0]}")

# Segundo INNER JOIN: el resultado anterior con aircraft_df
flights_routes_aircraft_merged = pd.merge(flights_routes_merged, aircraft_df, on='Aircraft_ID', how='inner')
print(f"Filas después de + aircraft_df (INNER): {flights_routes_aircraft_merged.shape[0]}")

print("\n--- Primeras filas del DataFrame combinado (Flights, Routes, Aircraft) ---")
display(flights_routes_aircraft_merged.head())
print("\n--- Información estructural del DataFrame combinado ---")
flights_routes_aircraft_merged.info()

Filas en flights_df: 50
Filas en routes_df: 20
Filas en aircraft_df: 8
Filas después de flights_df + routes_df (INNER): 50
Filas después de + aircraft_df (INNER): 50

--- Primeras filas del DataFrame combinado (Flights, Routes, Aircraft) ---

,Flight_ID,Route_ID,Aircraft_ID,Flight_Date,Passengers,Origin,Destination,Distance_Miles,Model,FuelCostperSeatMile,Capacity
0,1001,15,737,2026-03-13,277,ORD,ATL,780,Boeing 737,0.045,180
1,1002,2,737,2026-03-19,112,ORD,JFK,740,Boeing 737,0.045,180
2,1003,15,100,2026-01-16,74,ORD,ATL,780,Embraer E190,0.048,100
3,1004,20,787,2026-02-28,155,MIA,DEN,1350,Boeing 787 Dreamliner,0.035,280
4,1005,15,777,2026-02-03,195,ORD,ATL,780,Boeing 777,0.038,350

--- Información estructural del DataFrame combinado ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Flight_ID            50 non-null     int64
 1   Route_ID             50 non-null     int64
 2   Aircraft_ID          50 non-null     int64
 3   Flight_Date          50 non-null     datetime64[ns]
 4   Passengers           50 non-null     int64
 5   Origin               50 non-null     object
 6   Destination          50 non-null     object
 7   Distance_Miles       50 non-null     int64
 8   Model                50 non-null     object
 9   FuelCostperSeatMile  50 non-null     float64
 10  Capacity             50 non-null     int64
dtypes: datetime64[ns](1), float64(1), int64(6), object(3)
memory usage: 4.4+ KB

### Ejemplo: Creación de Clave Compuesta

A veces, ninguna columna individual es única para identificar una fila, pero una combinación de varias columnas sí lo es. En estos casos, podemos crear una *clave compuesta*.

In [55]:
print('\n--- Ejemplo de tabla sin clave única ---')
productos_ventas_df = pd.DataFrame({
    'ID_Producto': [101, 101, 102, 102, 103],
    'Tienda': ['A', 'A', 'B', 'A', 'C'],
    'Fecha': ['2023-01-01', '2023-01-01', '2023-01-02', '2023-01-02', '2023-01-03'],
    'Cantidad_Vendida': [10, 5, 8, 12, 7]
})
display(productos_ventas_df)

--- Ejemplo de tabla sin clave única ---

   ID_Producto Tienda       Fecha  Cantidad_Vendida
0          101      A  2023-01-01                10
1          101      A  2023-01-01                 5
2          102      B  2023-01-02                 8
3          102      A  2023-01-02                12
4          103      C  2023-01-03                 7

### Paso 1: Analizar la Unicidad de las Columnas Individuales

Primero, verificamos si alguna de las columnas existentes puede servir como clave única por sí sola. Una clave única significa que no hay valores duplicados en esa columna.

### Paso 2: Identificar la Necesidad de una Clave Compuesta

Como vemos, ninguna de las columnas (`ID_Producto`, `Tienda`, `Fecha`) es única por sí misma. Sin embargo, la combinación de `ID_Producto`, `Tienda` y `Fecha` sí identifica de manera única cada registro de venta (un producto vendido en una tienda específica en una fecha particular). Esto nos indica que necesitamos una clave compuesta.

### Paso 3: Verificar la Unicidad de la Clave Compuesta

Finalmente, confirmamos que la nueva columna `Clave_Compuesta` ahora sí actúa como un identificador único para cada fila.