In [15]:
import pandas as pd
import numpy as np

# Clase Completa: Modelado de Datos, Cardinalidad y Pandas
Este notebook cubre de forma exhaustiva los conceptos teóricos y prácticos sobre bases de datos relacionales y su implementación técnica en Python.

## ¿Qué es la Cardinalidad?
- En el diseño de bases de datos, define el número de entidades (filas) de una tabla que pueden asociarse con entidades de otra tabla a través de una relación.
- Determina las reglas de negocio y se expresa como 1:1, 1:N o M:N.

## Las Llaves del Modelo: PK y FK
- **Primary Key (PK):** Identificador único de un registro en su propia tabla (ej. `ID_Usuario`). No se puede repetir.
- **Foreign Key (FK):** Columna en una tabla secundaria que hace referencia a la PK de la tabla principal para permitir la unión física de los datos.

### Demostración de PK y FK en Pandas

In [16]:
productos_df = pd.DataFrame({
    'ID_Producto': [1, 2, 3], # Primary Key (PK)
    'Nombre_Producto': ['Leche', 'Pan', 'Huevos'],
    'Precio': [1.5, 2.0, 3.2]
})

ventas_df = pd.DataFrame({
    'ID_Venta': [101, 102, 103, 104],
    'ID_Producto': [1, 2, 1, 3], # Foreign Key (FK) referenciando ID_Producto en productos_df
    'Cantidad': [2, 1, 3, 1],
    'Fecha': ['2023-01-01', '2023-01-01', '2023-01-02', '2023-01-03']
})

print("Tabla de Productos (con PK 'ID_Producto'):")
display(productos_df)
print("\nTabla de Ventas (con FK 'ID_Producto'):")
display(ventas_df)

Tabla de Productos (con PK 'ID_Producto'):

   ID_Producto Nombre_Producto  Precio
0            1           Leche     1.5
1            2             Pan     2.0
2            3          Huevos     3.2

Tabla de Ventas (con FK 'ID_Producto'):

   ID_Venta  ID_Producto  Cantidad       Fecha
0       101            1         2  2023-01-01
1       102            2         1  2023-01-01
2       103            1         3  2023-01-02
3       104            3         1  2023-01-03

## Tipos de Cardinalidad (Mapa General)
1. Uno a Uno (1:1)
2. Uno a Muchos (1:N) o Muchos a Uno (N:1)
3. Muchos a Muchos (M:N)

### Visualización de Tipos de Cardinalidad

In [17]:
print("Los tipos fundamentales de cardinalidad son:")
print("1. Uno a Uno (1:1)")
print("2. Uno a Muchos (1:N)")
print("3. Muchos a Muchos (M:N)")

Los tipos fundamentales de cardinalidad son:
1. Uno a Uno (1:1)
2. Uno a Muchos (1:N)
3. Muchos a Muchos (M:N)

## Relación Uno a Uno (1:1)
- Un registro en la Tabla A se relaciona única y exclusivamente con un registro en la Tabla B, y viceversa.
- Se utiliza por motivos de seguridad, rendimiento o separación lógica de datos confidenciales.

### Ejemplo de Implementación 1:1 en Pandas

In [18]:
empleados_info_basica = pd.DataFrame({
    'ID_Empleado': [1, 2, 3],
    'Nombre': ['Alice', 'Bob', 'Charlie'],
    'Departamento': ['HR', 'Engineering', 'Marketing']
})

empleados_detalles_contrato = pd.DataFrame({
    'ID_Empleado': [1, 2, 3], # Misma PK, representando una relación 1:1
    'Fecha_Contrato': ['2020-01-15', '2019-06-01', '2021-03-10'],
    'Salario': [70000, 95000, 60000]
})

# Unimos las dos tablas usando el ID_Empleado
df_1_a_1 = pd.merge(empleados_info_basica, empleados_detalles_contrato, on='ID_Empleado', how='inner')

print("Tabla de Información Básica de Empleados:")
display(empleados_info_basica)
print("\nTabla de Detalles de Contrato (1:1 con Empleados):")
display(empleados_detalles_contrato)
print("\nResultado de la unión 1:1:")
display(df_1_a_1)

Tabla de Información Básica de Empleados:

   ID_Empleado   Nombre Departamento
0            1    Alice           HR
1            2      Bob  Engineering
2            3  Charlie    Marketing

Tabla de Detalles de Contrato (1:1 con Empleados):

   ID_Empleado Fecha_Contrato  Salario
0            1     2020-01-15    70000
1            2     2019-06-01    95000
2            3     2021-03-10    60000

Resultado de la unión 1:1:

   ID_Empleado   Nombre Departamento Fecha_Contrato  Salario
0            1    Alice           HR     2020-01-15    70000
1            2      Bob  Engineering     2019-06-01    95000
2            3  Charlie    Marketing     2021-03-10    60000

## Ejemplo Práctico de Relación 1:1 (Empleado y Expediente Médico)
- Un empleado tiene solo un expediente médico dentro de la empresa.
- Un expediente médico pertenece exactamente a un solo empleado.

### Ilustración de Empleado y Expediente Médico (1:1)

In [19]:
empleados_df = pd.DataFrame({
    'ID_Empleado': [1, 2],
    'Nombre_Empleado': ['Elena García', 'Juan Pérez']
})

expedientes_medicos_df = pd.DataFrame({
    'ID_Expediente': [1001, 1002],
    'ID_Empleado': [1, 2], # FK referenciando Empleado
    'Fecha_Ultima_Consulta': ['2023-05-10', '2023-04-22'],
    'Diagnostico_Principal': ['Gripe', 'Fractura']
})

df_empleado_expediente = pd.merge(empleados_df, expedientes_medicos_df, on='ID_Empleado', how='inner')

print("Tabla de Empleados:")
display(empleados_df)
print("\nTabla de Expedientes Médicos (1:1 con Empleados):")
display(expedientes_medicos_df)
print("\nUnión 1:1 de Empleados y Expedientes Médicos:")
display(df_empleado_expediente)

Tabla de Empleados:

   ID_Empleado Nombre_Empleado
0            1    Elena García
1            2      Juan Pérez

Tabla de Expedientes Médicos (1:1 con Empleados):

   ID_Expediente  ID_Empleado Fecha_Ultima_Consulta Diagnostico_Principal
0           1001            1            2023-05-10                 Gripe
1           1002            2            2023-04-22              Fractura

Unión 1:1 de Empleados y Expedientes Médicos:

,ID_Empleado,Nombre_Empleado,ID_Expediente,Fecha_Ultima_Consulta,Diagnostico_Principal
0,1,Elena García,1001,2023-05-10,Gripe
1,2,Juan Pérez,1002,2023-04-22,Fractura

## Ejemplo 2 de Relación 1:1 (Seguridad)
- Relación entre **Usuario** y **Credenciales de Acceso**.
- Se separan para evitar cargar información crítica y encriptada de seguridad en memoria durante consultas ordinarias.

### Ejemplo 1:1 para Seguridad (Usuario y Credenciales)

In [20]:
usuarios_df = pd.DataFrame({
    'ID_Usuario': [1, 2, 3],
    'Nombre_Usuario': ['admin', 'jdoe', 'mlee']
})

credenciales_df = pd.DataFrame({
    'ID_Usuario': [1, 2, 3], # FK referenciando Usuario
    'Hash_Contrasena': ['hash123', 'hash456', 'hash789'],
    'Ultimo_Login': ['2023-11-20', '2023-11-21', '2023-11-19']
})

df_usuario_credenciales = pd.merge(usuarios_df, credenciales_df, on='ID_Usuario', how='inner')

print("Tabla de Usuarios:")
display(usuarios_df)
print("\nTabla de Credenciales (1:1 con Usuarios):")
display(credenciales_df)
print("\nUnión 1:1 de Usuarios y Credenciales:")
display(df_usuario_credenciales)

Tabla de Usuarios:

   ID_Usuario Nombre_Usuario
0           1          admin
1           2           jdoe
2           3           mlee

Tabla de Credenciales (1:1 con Usuarios):

   ID_Usuario Hash_Contrasena Ultimo_Login
0           1         hash123   2023-11-20
1           2         hash456   2023-11-21
2           3         hash789   2023-11-19

Unión 1:1 de Usuarios y Credenciales:

   ID_Usuario Nombre_Usuario Hash_Contrasena Ultimo_Login
0           1          admin         hash123   2023-11-20
1           2           jdoe         hash456   2023-11-21
2           3           mlee         hash789   2023-11-19

## ¿Cómo Identificar una Relación 1:1?
- ¿Puede un elemento de la Tabla A tener más de un elemento de la Tabla B? **(No)**
- ¿Puede un elemento de la Tabla B pertenecer a más de un elemento de la Tabla A? **(No)**

### Identificando una Relación 1:1 - Una prueba sencilla

In [21]:
print("Para identificar 1:1:")
print("  ¿Cada fila de la Tabla A se asocia con UNA Y SOLO UNA fila de la Tabla B? Sí")
print("  ¿Cada fila de la Tabla B se asocia con UNA Y SOLO UNA fila de la Tabla A? Sí")
print("  Si ambas respuestas son 'Sí', es una relación 1:1.")

Para identificar 1:1:
  ¿Cada fila de la Tabla A se asocia con UNA Y SOLO UNA fila de la Tabla B? Sí
  ¿Cada fila de la Tabla B se asocia con UNA Y SOLO UNA fila de la Tabla A? Sí
  Si ambas respuestas son 'Sí', es una relación 1:1.

## Relación Uno a Muchos (1:N)
- Un registro en la Tabla A puede relacionarse con cero, uno o muchos registros en la Tabla B. Un registro en la Tabla B pertenece a un único registro de la Tabla A.
- Es el pilar fundamental del diseño de bases de datos relacionales.

### Estructura 1:N en DataFrames de Pandas

In [22]:
departamentos_df = pd.DataFrame({
    'ID_Departamento': [1, 2],
    'Nombre_Departamento': ['Ventas', 'Desarrollo']
})

empleados_df_1n = pd.DataFrame({
    'ID_Empleado': [101, 102, 103, 104],
    'Nombre': ['Laura', 'Pedro', 'Sofia', 'Miguel'],
    'ID_Departamento': [1, 1, 2, 2] # FK: ID_Departamento 1 y 2 aparecen múltiples veces
})

print("Tabla de Departamentos (el '1' en 1:N):")
display(departamentos_df)
print("\nTabla de Empleados (la 'N' en 1:N, mostrando la FK repetida):")
display(empleados_df_1n)

Tabla de Departamentos (el '1' en 1:N):

   ID_Departamento Nombre_Departamento
0                1              Ventas
1                2          Desarrollo

Tabla de Empleados (la 'N' en 1:N, mostrando la FK repetida):

   ID_Empleado  Nombre  ID_Departamento
0          101   Laura                1
1          102   Pedro                1
2          103   Sofia                2
3          104  Miguel                2

## Ejemplo Práctico de Relación 1:N (Clientes y Facturas)
- Un Cliente realiza muchas compras a lo largo del tiempo (muchas facturas).
- Una Factura específica es emitida a nombre de un solo cliente.

### Ejemplo Práctico 1:N (Clientes y Facturas) - Ver código anterior
El ejemplo en la celda `Pty4jdIE6f-8` ya demuestra esta relación.

## Estructura de Tablas en 1:N
- En la tabla Clientes, el ID aparece solo una vez.
- En la tabla Facturas, el ID aparece repetido como Clave Foránea (FK) en múltiples filas.

### Detalle de Estructura de Tablas para 1:N (Clientes y Facturas)

In [23]:
clientes_df_ej = pd.DataFrame({
    'ID_Cliente': [101, 102],
    'Nombre_Cliente': ['Ana Pérez', 'Carlos Gómez']
})

facturas_df_ej = pd.DataFrame({
    'ID_Factura': [5001, 5002, 5003],
    'Monto': [1500, 3200, 800],
    'ID_Cliente': [101, 101, 102] # ID_Cliente 101 se repite, 102 aparece una vez
})

print("Tabla 'Clientes' (el lado '1' de la relación - 'ID_Cliente' es PK):")
display(clientes_df_ej)
print("\nTabla 'Facturas' (el lado 'N' de la relación - 'ID_Cliente' es FK y se repite):")
display(facturas_df_ej)

df_resultado_1n = pd.merge(facturas_df_ej, clientes_df_ej, on='ID_Cliente', how='inner')
print("\nResultado de la unión 1:N:")
display(df_resultado_1n)

Tabla 'Clientes' (el lado '1' de la relación - 'ID_Cliente' es PK):

   ID_Cliente Nombre_Cliente
0         101      Ana Pérez
1         102   Carlos Gómez

Tabla 'Facturas' (el lado 'N' de la relación - 'ID_Cliente' es FK y se repite):

   ID_Factura  Monto  ID_Cliente
0        5001   1500         101
1        5002   3200         101
2        5003    800         102

Resultado de la unión 1:N:

   ID_Factura  Monto  ID_Cliente Nombre_Cliente
0        5001   1500         101      Ana Pérez
1        5002   3200         101      Ana Pérez
2        5003    800         102   Carlos Gómez

## Ejemplo 2 de Relación 1:N (Departamentos y Empleados)
- Un departamento tiene asignados a muchos empleados.
- Cada empleado trabaja en un único departamento a la vez.

### Ejemplo 1:N de Departamentos y Empleados en Pandas

In [24]:
dept_df = pd.DataFrame({
    'ID_Departamento': [1, 2, 3],
    'Nombre_Departamento': ['Recursos Humanos', 'Ingeniería', 'Marketing']
})

emp_df = pd.DataFrame({
    'ID_Empleado': [1, 2, 3, 4, 5],
    'Nombre_Empleado': ['Maria', 'Luis', 'Ana', 'Pedro', 'Sofia'],
    'ID_Departamento': [1, 2, 1, 3, 2] # Varios empleados en el mismo departamento
})

df_dept_emp = pd.merge(emp_df, dept_df, on='ID_Departamento', how='inner')

print("Tabla de Departamentos:")
display(dept_df)
print("\nTabla de Empleados:")
display(emp_df)
print("\nUnión 1:N de Departamentos y Empleados:")
display(df_dept_emp)

Tabla de Departamentos:

   ID_Departamento Nombre_Departamento
0                1    Recursos Humanos
1                2          Ingeniería
2                3           Marketing

Tabla de Empleados:

   ID_Empleado Nombre_Empleado  ID_Departamento
0            1           Maria                1
1            2            Luis                2
2            3             Ana                1
3            4           Pedro                3
4            5           Sofia                2

Unión 1:N de Departamentos y Empleados:

   ID_Empleado Nombre_Empleado  ID_Departamento Nombre_Departamento
0            1           Maria                1    Recursos Humanos
1            2            Luis                2          Ingeniería
2            3             Ana                1    Recursos Humanos
3            4           Pedro                3           Marketing
4            5           Sofia                2          Ingeniería

## ¿Cómo Identificar una Relación 1:N?
- De A hacia B: ¿Un Curso puede tener múltiples Estudiantes? **(Sí)**
- De B hacia A: ¿Un Estudiante pertenece a un único Curso? **(Sí)**

### ¿Cómo Identificar una Relación 1:N? - Un Vistazo Rápido

In [25]:
print("Para identificar 1:N:")
print("  De la Tabla A a la Tabla B: ¿Un elemento de A puede tener MÚLTIPLES elementos de B? (Ej. Un Cliente a muchas Facturas) -> Sí")
print("  De la Tabla B a la Tabla A: ¿Un elemento de B pertenece a UN SOLO elemento de A? (Ej. Una Factura a un solo Cliente) -> Sí")
print("  Si las respuestas son 'Sí' y 'Sí', respectivamente, es una relación 1:N.")

Para identificar 1:N:
  De la Tabla A a la Tabla B: ¿Un elemento de A puede tener MÚLTIPLES elementos de B? (Ej. Un Cliente a muchas Facturas) -> Sí
  De la Tabla B a la Tabla A: ¿Un elemento de B pertenece a UN SOLO elemento de A? (Ej. Una Factura a un solo Cliente) -> Sí
  Si las respuestas son 'Sí' y 'Sí', respectivamente, es una relación 1:N.

## Relación Muchos a Muchos (M:N)
- Múltiples registros en la Tabla A se asocian con múltiples registros en la Tabla B.
- **Requiere obligatoriamente** una tercera tabla intermedia llamada **Tabla de Unión o Puente** (Junction Table).

### La Estructura M:N con Tabla Puente en Pandas

In [26]:
estudiantes_df_mn = pd.DataFrame({
    'ID_Estudiante': [1, 2],
    'Nombre_Estudiante': ['Lucía', 'David']
})

cursos_df_mn = pd.DataFrame({
    'ID_Curso': [10, 20, 30],
    'Nombre_Curso': ['Álgebra', 'Literatura', 'Historia']
})

# Tabla Puente: inscripciones_df_mn
inscripciones_df_mn = pd.DataFrame({
    'ID_Estudiante': [1, 1, 2, 2], # Lucía (1) toma Álgebra (10) y Literatura (20)
    'ID_Curso': [10, 20, 20, 30]  # David (2) toma Literatura (20) e Historia (30)
})

print("Tabla de Estudiantes:")
display(estudiantes_df_mn)
print("\nTabla de Cursos:")
display(cursos_df_mn)
print("\nTabla Puente 'Inscripciones':")
display(inscripciones_df_mn)

Tabla de Estudiantes:

   ID_Estudiante Nombre_Estudiante
0              1             Lucía
1              2             David

Tabla de Cursos:

   ID_Curso Nombre_Curso
0        10      Álgebra
1        20   Literatura
2        30     Historia

Tabla Puente 'Inscripciones':

   ID_Estudiante  ID_Curso
0              1        10
1              1        20
2              2        20
3              2        30

## Ejemplo Práctico de Relación M:N (Estudiantes y Materias)
- Un Estudiante cursa muchas materias.
- Una Materia tiene inscritos a muchos estudiantes.

### Ejemplo Práctico M:N (Estudiantes y Materias) - Ver código anterior
El ejemplo en la celda `NtpwvFe9f-9` ya demuestra esta relación.

## Resolviendo el M:N con una Tabla Puente
- Se transforma el M:N en dos relaciones 1:N usando una tabla intermedia (ej. Inscripciones que almacena ambas FKs como PK compuesta).

### Resolviendo M:N con una Tabla Puente - Pasos en Pandas

In [27]:
estudiantes_df_res = pd.DataFrame({'ID_Estudiante': [1, 2], 'Nombre': ['Andrea', 'Bruno']})
materias_df_res = pd.DataFrame({'ID_Materia': [10, 20], 'Nombre_Materia': ['Matemáticas', 'Física']})
inscripciones_df_res = pd.DataFrame({'ID_Estudiante': [1, 1, 2], 'ID_Materia': [10, 20, 20]})

print("Tablas individuales:")
print("Estudiantes:"); display(estudiantes_df_res)
print("Materias:"); display(materias_df_res)
print("Inscripciones (Tabla Puente):"); display(inscripciones_df_res)

# Paso 1: Unir Estudiantes con la Tabla Puente
df_temp_res = pd.merge(estudiantes_df_res, inscripciones_df_res, on='ID_Estudiante', how='inner')
print("\nPaso 1: Estudiantes unidos con Inscripciones (1:N):")
display(df_temp_res)

# Paso 2: Unir el resultado con Materias
df_completo_res = pd.merge(df_temp_res, materias_df_res, on='ID_Materia', how='inner')
print("\nPaso 2: Resultado unido con Materias (1:N, completando el M:N):")
display(df_completo_res)

Tablas individuales:
Estudiantes:

   ID_Estudiante  Nombre
0              1  Andrea
1              2   Bruno

Materias:

   ID_Materia Nombre_Materia
0          10    Matemáticas
1          20         Física

Inscripciones (Tabla Puente):

   ID_Estudiante  ID_Materia
0              1          10
1              1          20
2              2          20

Paso 1: Estudiantes unidos con Inscripciones (1:N):

   ID_Estudiante  Nombre  ID_Materia
0              1  Andrea          10
1              1  Andrea          20
2              2   Bruno          20

Paso 2: Resultado unido con Materias (1:N, completando el M:N):

   ID_Estudiante  Nombre  ID_Materia Nombre_Materia
0              1  Andrea          10    Matemáticas
1              1  Andrea          20         Física
2              2   Bruno          20         Física

## Ejemplo 2 de Relación M:N (Productos y Órdenes de Compra)
- Un Pedido contiene muchos productos.
- Un Producto aparece en muchos pedidos distintos (Tabla puente: Detalle_Pedido con Cantidad y Precio Histórico).

### Ejemplo M:N de Productos y Órdenes de Compra con Tabla Puente

In [28]:
productos_compra_df = pd.DataFrame({
    'ID_Producto_C': [1, 2, 3],
    'Nombre_Producto_C': ['Camisa', 'Pantalón', 'Zapatos']
})

ordenes_compra_df = pd.DataFrame({
    'ID_Orden_C': [101, 102],
    'Fecha_Orden': ['2023-11-01', '2023-11-02']
})

detalle_orden_df = pd.DataFrame({
    'ID_Orden_C': [101, 101, 102, 102],
    'ID_Producto_C': [1, 2, 2, 3],
    'Cantidad': [1, 2, 1, 1]
})

# Unir órdenes con el detalle
df_orden_detalle = pd.merge(ordenes_compra_df, detalle_orden_df, on='ID_Orden_C', how='inner')
# Unir el resultado con los productos
df_orden_producto_completo = pd.merge(df_orden_detalle, productos_compra_df, on='ID_Producto_C', how='inner')

print("Tabla de Productos:")
display(productos_compra_df)
print("\nTabla de Órdenes de Compra:")
display(ordenes_compra_df)
print("\nTabla Puente 'Detalle de Orden':")
display(detalle_orden_df)
print("\nResultado Final de la Relación M:N (Ordenes y Productos):")
display(df_orden_producto_completo)

Tabla de Productos:

   ID_Producto_C Nombre_Producto_C
0              1            Camisa
1              2          Pantalón
2              3           Zapatos

Tabla de Órdenes de Compra:

   ID_Orden_C Fecha_Orden
0         101  2023-11-01
1         102  2023-11-02

Tabla Puente 'Detalle de Orden':

   ID_Orden_C  ID_Producto_C  Cantidad
0         101              1         1
1         101              2         2
2         102              2         1
3         102              3         1

Resultado Final de la Relación M:N (Ordenes y Productos):

   ID_Orden_C Fecha_Orden  ID_Producto_C  Cantidad Nombre_Producto_C
0         101  2023-11-01              1         1            Camisa
1         101  2023-11-01              2         2          Pantalón
2         102  2023-11-02              2         1          Pantalón
3         102  2023-11-02              3         1           Zapatos

## ¿Cómo Identificar una Relación M:N?
- ¿Un Actor participa en muchas Películas? **(Sí)**
- ¿Una Película tiene muchos Actores? **(Sí)**
- Dos Síes confirman un escenario M:N.

### Identificando una Relación M:N - La regla de los 'Dos Síes'

In [29]:
print("Para identificar M:N:")
print("  De la Tabla A a la Tabla B: ¿Un elemento de A puede tener MÚLTIPLES elementos de B? -> Sí")
print("  De la Tabla B a la Tabla A: ¿Un elemento de B puede tener MÚLTIPLES elementos de A? -> Sí")
print("  Si AMBAS respuestas son 'Sí', es una relación M:N. ¡Necesitas una tabla puente!")

Para identificar M:N:
  De la Tabla A a la Tabla B: ¿Un elemento de A puede tener MÚLTIPLES elementos de B? -> Sí
  De la Tabla B a la Tabla A: ¿Un elemento de B puede tener MÚLTIPLES elementos de A? -> Sí
  Si AMBAS respuestas son 'Sí', es una relación M:N. ¡Necesitas una tabla puente!

## Tabla Resumen de Identificación
- Máximo Uno $\leftrightarrow$ Máximo Uno = **1:1**
- Máximo Muchos $\leftrightarrow$ Máximo Uno = **1:N**
- Máximo Muchos $\leftrightarrow$ Máximo Muchos = **M:N**

### Visualización de la Tabla Resumen de Identificación

In [30]:
resumen_cardinalidad = pd.DataFrame({
    'Relación de A a B': ['Máximo Uno', 'Máximo Muchos', 'Máximo Muchos'],
    'Relación de B a A': ['Máximo Uno', 'Máximo Uno', 'Máximo Muchos'],
    'Tipo de Cardinalidad': ['1:1', '1:N', 'M:N']
})

print("Tabla Resumen para la Identificación de Cardinalidad:")
display(resumen_cardinalidad)

Tabla Resumen para la Identificación de Cardinalidad:

  Relación de A a B Relación de B a A Tipo de Cardinalidad
0        Máximo Uno        Máximo Uno                  1:1
1     Máximo Muchos        Máximo Uno                  1:N
2     Máximo Muchos     Máximo Muchos                  M:N

## Sección II: Uniendo Tablas en Python con Pandas

In [31]:
# Importación de librerías
import pandas as pd
import numpy as np

print("Librerías listas para la práctica.")

Librerías listas para la práctica.

In [32]:
# Tip 1: Implementando Relaciones 1:N con pd.merge()
clientes_df = pd.DataFrame({
    'ID_Cliente': [101, 102],
    'Nombre_Cliente': ['Ana Pérez', 'Carlos Gómez']
})

facturas_df = pd.DataFrame({
    'ID_Factura': [5001, 5002, 5003],
    'Monto': [1500, 3200, 800],
    'ID_Cliente': [101, 101, 102]
})

df_resultado = pd.merge(facturas_df, clientes_df, on='ID_Cliente', how='inner')
print("Cruce relacional 1:N:")
display(df_resultado)

Cruce relacional 1:N:

   ID_Factura  Monto  ID_Cliente Nombre_Cliente
0        5001   1500         101      Ana Pérez
1        5002   3200         101      Ana Pérez
2        5003    800         102   Carlos Gómez

In [33]:
# Tip 2: Resolución de Relaciones M:N en Python mediante Cruces Sucesivos
estudiantes_df = pd.DataFrame({'ID_Estudiante': [1, 2], 'Nombre': ['Sofía', 'Mateo']})
materias_df = pd.DataFrame({'ID_Materia': [10, 20], 'Nombre_Materia': ['Cálculo', 'Programación']})
inscripciones_df = pd.DataFrame({'ID_Estudiante': [1, 1, 2], 'ID_Materia': [10, 20, 20]})

df_temp = pd.merge(estudiantes_df, inscripciones_df, on='ID_Estudiante')
df_completo = pd.merge(df_temp, materias_df, on='ID_Materia')

print("Resolución de M:N con Tabla Puente:")
display(df_completo)

Resolución de M:N con Tabla Puente:

   ID_Estudiante Nombre  ID_Materia Nombre_Materia
0              1  Sofía          10        Cálculo
1              1  Sofía          20   Programación
2              2  Mateo          20   Programación

In [34]:
# Tip 3: Optimización de Memoria y Tipos de Datos
df = pd.DataFrame({
    'Pais_Origen': ['Chile', 'México', 'Colombia', 'Argentina'] * 50000,
    'Likes': np.random.randint(0, 500, size=200000)
})

print("Memoria ANTES:")
display(df.memory_usage(deep=True))

df['Pais_Origen'] = df['Pais_Origen'].astype('category')

print("\nMemoria DESPUÉS de optimizar a 'category':")
display(df.memory_usage(deep=True))

Memoria ANTES:

Index               132
Pais_Origen    12000000
Likes           1600000
dtype: int64

Memoria DESPUÉS de optimizar a 'category':

Index              132
Pais_Origen     200420
Likes          1600000
dtype: int64

In [35]:
# Caso Práctico de Cierre: Análisis de Redes Sociales en Python
fact_interacciones = pd.DataFrame({
    'ID_Interaccion': [9001, 9002, 9003],
    'ID_Usuario': [101, 102, 101],
    'Likes': [45, 12, 89],
    'Comentario_Libre': ['Excelente', 'Muy bueno', 'Me encanta']
})

dim_usuarios = pd.DataFrame({
    'ID_Usuario': [101, 102],
    'Pais_Origen': ['Chile', 'México']
})

# Limpieza de columna de alta cardinalidad innecesaria
fact_limpio = fact_interacciones.drop(columns=['Comentario_Libre'])

# Consolidación y agregación
df_final = pd.merge(fact_limpio, dim_usuarios, on='ID_Usuario')
resumen_paises = df_final.groupby('Pais_Origen')['Likes'].sum().reset_index()

print("Caso Práctico - Resumen de Likes por País:")
display(resumen_paises)

Caso Práctico - Resumen de Likes por País:

  Pais_Origen  Likes
0       Chile    134
1      México     12