In [33]:
import os
import pandas as pd

## Etapa 1: Creación de la "Base de Datos" (Archivos de Prueba)

### Nota Importante: Instalación de Librerías Adicionales
Para guardar archivos en formato Excel (.xlsx), la librería `pandas` requiere `openpyxl`.
Si no la tienes instalada, puedes ejecutar la siguiente celda para instalarla:

In [34]:
# !pip install openpyxl

### Paso 1: Generar el archivo de ventas `ventas.csv`

In [35]:
print("--- ETAPA 1: Generando archivos de prueba locales ---")

# 1. Crear el archivo de ventas 'ventas.csv' con separador ';' tal como indica la presentación.
# Agregamos intencionalmente registros con márgenes negativos para nuestro caso práctico de cierre.
datos_ventas = {
    'Producto': ['Teclado Mecánico', 'Monitor 4K', 'Mouse Gamer', 'Silla Ergonómica', 'Auriculares Pro', 'Cable HDMI'],
    'Mes': ['Ene', 'Ene', 'Feb', 'Feb', 'Mar', 'Mar'],
    'Ingresos': [12000, 45000, 8000, 35000, 15000, 1200],
    'Costos': [9000, 48000, 5000, 28000, 16500, 800]  # El monitor y los auriculares tienen pérdidas (costo > ingresos)
}

df_ventas_inicial = pd.DataFrame(datos_ventas)

print("DataFrame de ventas inicial creado:")
display(df_ventas_inicial)

--- ETAPA 1: Generando archivos de prueba locales ---
DataFrame de ventas inicial creado:

           Producto  Mes  Ingresos  Costos
0  Teclado Mecánico  Ene     12000    9000
1        Monitor 4K  Ene     45000   48000
2       Mouse Gamer  Feb      8000    5000
3  Silla Ergonómica  Feb     35000   28000
4   Auriculares Pro  Mar     15000   16500
5        Cable HDMI  Mar      1200     800

In [36]:
df_ventas_inicial.to_csv('ventas.csv', index=False, sep=';', encoding='utf-8')
print("✅ Archivo 'ventas.csv' generado exitosamente.")

✅ Archivo 'ventas.csv' generado exitosamente.

In [37]:
df_ventas_inicial.to_excel('ventas.xlsx', index=False)
print("✅ Archivo 'ventas.xlsx' generado exitosamente.")

✅ Archivo 'ventas.xlsx' generado exitosamente.

### Paso 2: Generar el archivo de presupuesto `presupuesto.xlsx`

In [38]:
# 2. Crear el archivo de presupuesto 'presupuesto.xlsx' con una pestaña llamada 'Q1'.
datos_presupuesto = {
    'Departamento': ['Tecnología', 'Marketing', 'Operaciones', 'Recursos Humanos'],
    'Presupuesto_Asignado': [50000, 25000, 40000, 15000],
    'Ejecutado': [42000, 26000, 38000, 14500]
}

df_presupuesto_inicial = pd.DataFrame(datos_presupuesto)

print("DataFrame de presupuesto inicial creado:")
display(df_presupuesto_inicial)

DataFrame de presupuesto inicial creado:

       Departamento  Presupuesto_Asignado  Ejecutado
0        Tecnología                 50000      42000
1         Marketing                 25000      26000
2       Operaciones                 40000      38000
3  Recursos Humanos                 15000      14500

In [39]:
with pd.ExcelWriter('presupuesto.xlsx', engine='openpyxl') as writer:
    df_presupuesto_inicial.to_excel(writer, sheet_name='Q1', index=False)
print("✅ Archivo 'presupuesto.xlsx' (hoja Q1) generado exitosamente.")
print("-" * 60 + "\n")

✅ Archivo 'presupuesto.xlsx' (hoja Q1) generado exitosamente.
------------------------------------------------------------

## Etapa 2: Demostración de Conceptos Básicos de Python

In [40]:
print("--- ETAPA 2: Conceptos Básicos de Python ---")

--- ETAPA 2: Conceptos Básicos de Python ---

### Paso 1: Entorno de Desarrollo y Sintaxis Básica

In [41]:
ingresos = 150000
costos = 90000
print(f"Sintaxis Básica -> Ingresos: {ingresos} | Costos: {costos}")

Sintaxis Básica -> Ingresos: 150000 | Costos: 90000

### Paso 2: Tipos de Datos Primitivos y Operaciones

In [42]:
entero_id = 101                 # int
tasa_interes = 0.15             # float
centro_costo = "Norte_Ventas"   # str
activo = True                   # bool
hoy = "2026-09-22"              # str

# Gringos: 9/11/2001, Chile: 11/09/2001, 11-09-2001. Usar el formato yyyy-mm-dd, yyyymmdd

# Operaciones matemáticas
suma_ingresos = ingresos + 25000
potencia = 5 ** 2               # 5 al cuadrado
division_entera = 10 // 3       # Devuelve 3
modulo = 10 % 3                 # Devuelve el residuo (1)

print(f"Tipos de Datos -> ID: {entero_id}, Tasa: {tasa_interes}, Centro de costo: '{centro_costo}', Estado: {activo}")
print(f"Aritmética -> Suma: {suma_ingresos}, Potencia (5^2): {potencia}, Div. Entera: {division_entera}, Módulo: {modulo}")

Tipos de Datos -> ID: 101, Tasa: 0.15, Centro de costo: 'Norte_Ventas', Estado: True
Aritmética -> Suma: 175000, Potencia (5^2): 25, Div. Entera: 3, Módulo: 1

### Paso 3: Estructuras de Datos: Listas y Diccionarios

In [43]:
# Listas (Indexación base cero)
meses = ['Ene', 'Feb', 'Mar']
primer_mes = meses[0]  # Acceso a 'Ene'
print(f"Listas -> Meses cargados: {meses} | Primer elemento (índice 0): {primer_mes}")

# Diccionarios (Estructuras clave-valor)
kpi = {
    'nombre': 'EBITDA',
    'valor': 25000
}
print(f"Diccionarios -> Clave 'nombre': {kpi['nombre']} | Clave 'valor': {kpi['valor']}")

Listas -> Meses cargados: ['Ene', 'Feb', 'Mar'] | Primer elemento (índice 0): Ene
Diccionarios -> Clave 'nombre': EBITDA | Clave 'valor': 25000

### Paso 4: Estructuras de Control: Sentencias Condicionales

In [44]:
margen = (ingresos - costos) / ingresos
cumple_porcentaje = 0.95

# Control de flujo con indentación estricta de Python
print("\nEjecutando lógica de condiciones (IF-ELIF-ELSE):")
if margen > 0.2:
    print(" -> Margen Saludable")
elif cumple_porcentaje >= 1.0:
    bono = 100
elif cumple_porcentaje >= 0.9:
    bono = 50
else:
    print(" -> Alerta de Margen")
    bono = 0

Ejecutando lógica de condiciones (IF-ELIF-ELSE):
 -> Margen Saludable

### Paso 5: Bucles e Iteraciones (WHILE y FOR)

In [45]:
print("\nEjecutando iteraciones (Bucles):")
saldo = 0
meta = 1000
ahorro = 350

# Bucle WHILE
while saldo < meta:
    saldo += ahorro
print(f" -> Bucle WHILE finalizado. Saldo final acumulado: {saldo} (Meta: {meta})")

# Bucle FOR
print(" -> Bucle FOR recorriendo lista:")
for mes in meses:
    print(f"    - Mes del año analizado: {mes}")

Ejecutando iteraciones (Bucles):
 -> Bucle WHILE finalizado. Saldo final acumulado: 1050 (Meta: 1000)
 -> Bucle FOR recorriendo lista:
    - Mes del año analizado: Ene
    - Mes del año analizado: Feb
    - Mes del año analizado: Mar

### Paso 6: Funciones

In [46]:
def calc_margen(ing, cost):
    """Calcula la tasa del margen basada en ingresos y costos"""
    return (ing - cost) / ing

margen_calculado = calc_margen(ingresos, costos)
print(f"\nFunciones -> El margen calculado por función es: {margen_calculado:.2%}")
print("-" * 60 + "\n")

Funciones -> El margen calculado por función es: 40.00%
------------------------------------------------------------

## Etapa 3: Análisis y Manipulación de Datos con Pandas

In [47]:
print("--- ETAPA 3: Manipulación de Datos con Pandas ---")

--- ETAPA 3: Manipulación de Datos con Pandas ---

### Paso 1: Lectura de Archivos

In [48]:
df_csv = pd.read_csv('ventas.csv', sep=';')
df_excel = pd.read_excel('presupuesto.xlsx', sheet_name='Q1')

print("📂 Carga de datos exitosa.")
print("Datos de Ventas en CSV:")
print(df_csv)

📂 Carga de datos exitosa.
Datos de Ventas en CSV:
           Producto  Mes  Ingresos  Costos
0  Teclado Mecánico  Ene     12000    9000
1        Monitor 4K  Ene     45000   48000
2       Mouse Gamer  Feb      8000    5000
3  Silla Ergonómica  Feb     35000   28000
4   Auriculares Pro  Mar     15000   16500
5        Cable HDMI  Mar      1200     800

### Paso 2: Exploración Inicial del DataFrame

In [49]:
print("\nExploración Inicial (Método .head()):")
print(df_csv.head(2))

print("\nExploración Inicial (Método .info() resumido):")
df_csv.info()

print("\nExploración Inicial (Método .describe() de variables numéricas):")
print(df_csv.describe())

Exploración Inicial (Método .head()):
           Producto  Mes  Ingresos  Costos
0  Teclado Mecánico  Ene     12000    9000
1        Monitor 4K  Ene     45000   48000

Exploración Inicial (Método .info() resumido):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Producto  6 non-null      object
 1   Mes       6 non-null      object
 2   Ingresos  6 non-null      int64
 3   Costos    6 non-null      int64
dtypes: int64(2), object(2)
memory usage: 324.0+ bytes

Exploración Inicial (Método .describe() de variables numéricas):
           Ingresos        Costos
count      6.000000      6.000000
mean   19366.666667  17883.333333
std    16935.367332  17595.501319
min     1200.000000    800.000000
25%     9000.000000   6000.000000
50%    13500.000000  12750.000000
75%    30000.000000  25125.000000
max    45000.000000  48000.000000

### Paso 3: Selección, Segmentación y Operaciones Vectorizadas

In [50]:
# Selección de Variables de Interés (Columnas)
columna_ingresos = df_csv['Ingresos']
columnas_multiples = df_csv[['Mes', 'Ingresos']]
print("\nSelección de Columnas (ejemplo 'Ingresos'):")
print(columna_ingresos.head())
print("\nSelección de Múltiples Columnas (ejemplo 'Mes', 'Ingresos'):")
print(columnas_multiples.head())

Selección de Columnas (ejemplo 'Ingresos'):
0    12000
1    45000
2     8000
3    35000
4    15000
Name: Ingresos, dtype: int64

Selección de Múltiples Columnas (ejemplo 'Mes', 'Ingresos'):
   Mes  Ingresos
0  Ene     12000
1  Ene     45000
2  Feb      8000
3  Feb     35000
4  Mar     15000

In [51]:
# Selección de Filas por Índices
filas_posicion = df_csv.iloc[0:3]    # Por posición física (exclusivo en el extremo derecho)
filas_etiqueta = df_csv.loc[0:3]     # Por etiqueta de índice (inclusivo)
print("\nSelección de Filas por Posición (primeras 3):\n",filas_posicion)
print("\nSelección de Filas por Etiqueta (primeras 4):\n",filas_etiqueta)

Selección de Filas por Posición (primeras 3):
            Producto  Mes  Ingresos  Costos
0  Teclado Mecánico  Ene     12000    9000
1        Monitor 4K  Ene     45000   48000
2       Mouse Gamer  Feb      8000    5000

Selección de Filas por Etiqueta (primeras 4):
            Producto  Mes  Ingresos  Costos
0  Teclado Mecánico  Ene     12000    9000
1        Monitor 4K  Ene     45000   48000
2       Mouse Gamer  Feb      8000    5000
3  Silla Ergonómica  Feb     35000   28000

In [52]:
# Operación Vectorizada: Cálculos directos sin bucles FOR
df_csv['Resultado'] = df_csv['Ingresos'] - df_csv['Costos']
print("\nDataFrame con columna calculada de forma vectorizada ('Resultado'):")
print(df_csv[['Producto', 'Ingresos', 'Costos', 'Resultado']])

DataFrame con columna calculada de forma vectorizada ('Resultado'):
           Producto  Ingresos  Costos  Resultado
0  Teclado Mecánico     12000    9000       3000
1        Monitor 4K     45000   48000      -3000
2       Mouse Gamer      8000    5000       3000
3  Silla Ergonómica     35000   28000       7000
4   Auriculares Pro     15000   16500      -1500
5        Cable HDMI      1200     800        400

In [53]:
# Filtrado Lógico de Datos
df_alto_ingreso = df_csv[df_csv['Ingresos'] > 10000]
print("\nFiltrado Lógico (Ingresos > 10000):")
print(df_alto_ingreso)

Filtrado Lógico (Ingresos > 10000):
           Producto  Mes  Ingresos  Costos  Resultado
0  Teclado Mecánico  Ene     12000    9000       3000
1        Monitor 4K  Ene     45000   48000      -3000
3  Silla Ergonómica  Feb     35000   28000       7000
4   Auriculares Pro  Mar     15000   16500      -1500

In [61]:
# Filtrado Lógico de Datos
df_alto_ingreso1 = df_csv[df_csv['Ingresos'] > 10000]
df_alto_ingreso1 = df_alto_ingreso1.reset_index(drop=True)
print("\nFiltrado Lógico (Ingresos > 10000):")
print(df_alto_ingreso1)

Filtrado Lógico (Ingresos > 10000):
           Producto  Mes  Ingresos  Costos  Resultado
0  Teclado Mecánico  Ene     12000    9000       3000
1        Monitor 4K  Ene     45000   48000      -3000
2  Silla Ergonómica  Feb     35000   28000       7000
3   Auriculares Pro  Mar     15000   16500      -1500

### Paso 4: Exportación de Resultados

In [55]:
df_csv.to_excel('reporte_procesado.xlsx', index=False)
print("\n💾 Archivo 'reporte_procesado.xlsx' guardado de forma preliminar.")
print("-" * 60 + "\n")

💾 Archivo 'reporte_procesado.xlsx' guardado de forma preliminar.
------------------------------------------------------------

## Etapa 4: Caso Práctico de Cierre

In [56]:
print("--- ETAPA 4: Ejecución del Caso Práctico de Cierre ---")

--- ETAPA 4: Ejecución del Caso Práctico de Cierre ---

### Paso 1: Lectura de los datos de ventas

In [57]:
df_origen = pd.read_csv('ventas.csv', sep=';')
print("1. Datos originales cargados correctamente.")

1. Datos originales cargados correctamente.

### Paso 2: Cálculo de ganancias y márgenes

In [58]:
df_origen['Ganancia_Netas'] = df_origen['Ingresos'] - df_origen['Costos']
df_origen['Margen_Ganancia'] = (df_origen['Ingresos'] - df_origen['Costos']) / df_origen['Ingresos']
print("2. Columnas de ganancias y márgenes calculadas de forma vectorizada.")

2. Columnas de ganancias y márgenes calculadas de forma vectorizada.

### Paso 3: Filtrado de anomalías (márgenes negativos)

In [59]:
# Al usar la condición < 0, aislamos los productos que están reportando pérdidas
alertas_margen_negativo = df_origen[df_origen['Margen_Ganancia'] < 0]
print("\n3. Alertas de anomalías detectadas (Márgenes Negativos):")
print(alertas_margen_negativo[['Producto', 'Ingresos', 'Costos', 'Margen_Ganancia']])

3. Alertas de anomalías detectadas (Márgenes Negativos):
          Producto  Ingresos  Costos  Margen_Ganancia
1       Monitor 4K     45000   48000        -0.066667
4  Auriculares Pro     15000   16500        -0.100000

### Paso 4: Exportación de alertas críticas a Excel

In [60]:
alertas_margen_negativo.to_excel('alertas_criticas_margen.xlsx', index=False)
print("\n💾 4. Caso Práctico Terminado. Reporte 'alertas_criticas_margen.xlsx' exportado con éxito.")
print("=" * 60)

💾 4. Caso Práctico Terminado. Reporte 'alertas_criticas_margen.xlsx' exportado con éxito.
============================================================